stages:
  data_cleaning:
    cmd: python src/data/data_cleaning.py
    deps:
    - data/raw/swiggy.csv
    - src/data/data_cleaning.py
    outs:
    - data/cleaned/swiggy_cleaned.csv
  data_preparation:
    cmd: python src/data/data_preparation.py
    deps:
    - params.yaml
    - data/cleaned/swiggy_cleaned.csv
    - src/data/data_preparation.py
    outs:
    - data/interim/test.csv
    - data/interim/train.csv
  data_preprocessing:
    cmd: python src/features/data_preprocessing.py
    deps:
    - data/interim/test.csv
    - data/interim/train.csv
    - src/features/data_preprocessing.py
    outs:
    - data/processed/test_trans.csv
    - data/processed/train_trans.csv
    - models/preprocessor.joblib
